[workspace]
members = [
    "apps/server",
    "crates/streaming-files",
    "apps/client-react-native/rust",
    "crates/hook-transpiler",
    "crates/hook-transpiler-cli",
    "crates/themed-styler",
]
resolver = "2"
