apiVersion: v1
clusters:
  - cluster:
      insecure-skip-tls-verify: false
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTEVrOFBXcGVRc1F3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1qUXhNakl3TXpGYUZ3MHpOVEV4TWpJeE1qSTFNekZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNrMCs0dlBRZmtKU1dBcE9tOW5YTHdIbmY3cWVkSGJnNGlhTUpDSUNybDExS1IzUG40aWI1YXlLM3IKWGEyRlpvR01oaWhaektzVnJCd3JGU3l3QUN4K0VHTDBxaGVSSW8xTzZVMVdMZHlWa3Bod0dwWEpreGtQUFR4bwowUDU4ck1Oc2pPNzBRelZDY044UGlqY3UxdEM3c0Iwd0pPenBHR05rZnhqRnNZMUJjR1o2MGdUaENTbjVMTFhKCjlPczc0blhaRG5xeS9IaGVpelN1M3FlampGdW1YUDg0SG9YdjdzNVFSNWpWNVNEZjRqcTE0VGdIR2J2b09EWXIKUDVEaE5LcjdHc0N5b09WdWtPckM4WnVvS3lwOHRMcGpTRUJFRXk5K2ZiejRYd0dKRjBOT21mVlRDU3VuSm90awphS1EvN0tDVTlLcWFuVktYaGx4VWhQVFFjV1VSQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRYTlGeWkwdVFoMWFTSmhMdSsvYUlYQVRBMGZqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQlllUjU2VXZUVQpRVmtrLzArM0o5T2FnSVhqTEF3QVJBWnBsU0h6RHU0WlpMVnVmdUlPWll6UDAyRUxFU1VnZlVWOWUwektxY1kwCmtlQVZ3QXprYnZaTTI3czR1YmRxZVZIZVliSC8xTUFXUUo5WWZWY2Z4Y0xQQURxYW1WUFMzVVN6YkE0VTVjRXgKcmlDT3lNVytOdEQrNGU3ZTl4MXk1bDMvUzVOL2dKME5sTzRRRFVmaXNsQkdKVzRMc3l4QmdveCtFcFVqcGgvaQpqQkEvTU5vdmlzRFU4WHpLY3RpRG8xV1drcmwzalEwcGl5YytYYngrMjR6Zy9WbytqeXJHNTd2dkN6WXBlcUIvCkxaSnU4NisvTHN4dDhWcFZTZ3grZ3Q3SXFBQy93VVRITnJLQXhDMTAzc1lzZDNXbHp6TldMYzJIUG1XQXFkb0MKNlV1RTJ1TE9OaUt6Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://hcp-629ba0a6-b40a-415c-a74a-9a7dec6a4a3b.spot.rackspace.com/
    name: relay-test
contexts:
  - context:
      cluster: relay-test
      namespace: default
      user: ngpc-user
    name: clevertree-relay-test
  - context:
      cluster: relay-test
      namespace: default
      user: oidc
    name: clevertree-relay-test-oidc
current-context: clevertree-relay-test
kind: Config
preferences: {}
users:
  - name: ngpc-user
    user:
      token: >-
        eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNYQ25nd1NFS0JWQl9DbWxvalo0eCJ9.eyJncm91cCI6ImNsb3Vkc3BhY2UtYWRtaW4iLCJuaWNrbmFtZSI6ImNsZXZlcnRyZWUiLCJuYW1lIjoiQXJpIEFzdWxpbiIsInBpY3R1cmUiOiJodHRwczovL2F2YXRhcnMuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3UvMTk1OTA3MD92PTQiLCJ1cGRhdGVkX2F0IjoiMjAyNS0xMS0yNlQxNDoxNzowMS4yNTlaIiwiZW1haWwiOiJhcmkuYXN1bGluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczovL2xvZ2luLnNwb3QucmFja3NwYWNlLmNvbS8iLCJhdWQiOiJtd0czbFVNVjhLeWVNcUhlNGZKNUJiM25NMXZCdlJOYSIsInN1YiI6ImdpdGh1YnwxOTU5MDcwIiwiaWF0IjoxNzY0MjQ0NTI3LCJleHAiOjE3NjQ1MDM3MjcsInNpZCI6IkVvWkx5MUhQNFVtVVJYRVpZZEpfdzBPVzd6RFlBM3VsIiwibm9uY2UiOiJiMkV6VFVJd09WQk5hekpRVXprMFFXcHJWM2MyYjBSbmExVjJhVWh0VG1acVQzRjVUVXhHTlc5WFp3PT0iLCJvcmdfaWQiOiJvcmdfNWJWZ2ZkN2ZJN2lZWWoyWCJ9.eEjmgs9LmPLb2DX_lKsaHtpq2fOXo6XWtX2CQnkvbZkwx6VK7OS_vp-hPJa7UjMX6XcqgJD-8VlFSjvRVvU9_3PjplPWbqlhrNZwZOuGJEftHJ9EYMHfTC62YXZL7uA4inIs0R34L9qZR0FjYDfgRA01HhaFa2HfBuvXhz08EUQDFLBIXrUPF3VBqyGJKVLEbFO-pZbksvzvA0kedfdcXxdH5YRLYAVKfZZ1RMJSD4XqoGfgsPZuED_q5tUHUojl7PpMhGKWqavvuT25UDjKZZWfflGqOqyJGTbyfgu769pDLdbhlFDJJA0Jc5Bry3WvwevXKS8x-xlVUSBN3FI5Rg
  - name: oidc
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          - '--oidc-issuer-url=https://login.spot.rackspace.com/'
          - '--oidc-client-id=mwG3lUMV8KyeMqHe4fJ5Bb3nM1vBvRNa'
          - '--oidc-extra-scope=openid'
          - '--oidc-extra-scope=profile'
          - '--oidc-extra-scope=email'
          - '--oidc-auth-request-extra-params=organization=org_5bVgfd7fI7iYYj2X'
          - '--token-cache-dir=~/.kube/cache/oidc-login/org_5bVgfd7fI7iYYj2X'
        command: kubectl
        env: null
        interactiveMode: IfAvailable
        provideClusterInfo: false
