[workspace]

[package]
name = "wasm_hook_transpiler"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[patch.crates-io]
serde = { path = "patches/serde" }

[dependencies]
wasm-bindgen = "0.2"
hook-transpiler = { path = "../../../crates/hook-transpiler" }
