[package]
name = "relay-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
bytes = "1"
relay-lib = { path = "../relay-lib" }
serde_json = "1"
