[package]
name = "relay-client-rn-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
name = "relay_client_rn_core"
crate-type = ["cdylib", "staticlib"]

[dependencies]
